T = 120 # Steps Internet blackout = 5days 5 * 24 / 120 = 1 hours
N = 600 # users
A = 25 # X
B = 25 # Y
WORLD_DIMENSION = (A, B)
r = 2
MOVE_RANGE = ((-r, r), (-r, r))
d = 1
MESSAGE_EXCHANGE_RANGE = ((-d, d), (-d, d))
ADVERSARY_RATIO = 0.02

# TODO: new
JAMMING_ATTACK = False

# Watts-Strogatz model parameters
WS_DELTA = 15
# WS_DELTA = N // 10
WS_BETA = 0.5

# User settings
MESSAGE_STORAGE_SIZE = 5000
MAX_VOTES_ALLOWED_ON_MESSAGE = 600


MIN_TTL = T + 20
USER_MESSAGE_CREATION_RATE = 0.05
USER_ACT_PROBABILITY = 0.15

OWT_MIN_TRUST_VALUE = 4
OWT_MIN_UP_RATIO = 0.66
# 10 UP - 6 D
UPVOTE_MIN_TRUST_VALUE = 2
UPVOTE_MIN_UP_RATIO = 0.55

OLD_MESSAGE_CUTOFF = 24 # hours

# Program related
UPVOTE = True
DOWNVOTE = False

# User awareness settings

TEST_NAME = "STANDARD"
ADVERSARY_FRIEND_REDUCTION = 0.4 
USER_VOTING_ON_UNKNOWN_MESSAGES_RATE = 0.05 
USER_UPVOTING_ON_MISINFORMATION_RATE = 0.3 
USER_UPVOTING_ON_NORMAL_RATE = 0.6 

# TEST_NAME = "GULLIBLE"
# ADVERSARY_FRIEND_REDUCTION = 0.7
# USER_VOTING_ON_UNKNOWN_MESSAGES_RATE = 0.1
# USER_UPVOTING_ON_MISINFORMATION_RATE = 0.4 
# USER_UPVOTING_ON_NORMAL_RATE = 0.55

# TEST_NAME = "SMART"
# ADVERSARY_FRIEND_REDUCTION = 0.2
# USER_VOTING_ON_UNKNOWN_MESSAGES_RATE = 0.02
# USER_UPVOTING_ON_MISINFORMATION_RATE = 0.2
# USER_UPVOTING_ON_NORMAL_RATE = 0.7


# TEST_NAME = "SUPER GULLIBLE"
# ADVERSARY_FRIEND_REDUCTION = 0.9
# USER_VOTING_ON_UNKNOWN_MESSAGES_RATE = 0.2
# USER_UPVOTING_ON_MISINFORMATION_RATE = 0.5 
# USER_UPVOTING_ON_NORMAL_RATE = 0.5

# TEST_NAME = "SUPER SMART"
# ADVERSARY_FRIEND_REDUCTION = 0.1
# USER_VOTING_ON_UNKNOWN_MESSAGES_RATE = 0.01
# USER_UPVOTING_ON_MISINFORMATION_RATE = 0.1
# USER_UPVOTING_ON_NORMAL_RATE = 0.8